/**
 * GitHub's language colours (github-linguist, languages.yml) for the languages DevCity is most
 * likely to meet. Unknown languages get a stable colour derived from their name.
 */
const colors: Record<string, string> = {
  Astro: '#ff5a03',
  Batchfile: '#c1f12e',
  C: '#555555',
  'C#': '#178600',
  'C++': '#f34b7d',
  CSS: '#663399',
  Clojure: '#db5855',
  CoffeeScript: '#244776',
  Dart: '#00b4ab',
  Dockerfile: '#384d54',
  Elixir: '#6e4a7e',
  Elm: '#60b5cc',
  Erlang: '#b83998',
  'F#': '#b845fc',
  Go: '#00add8',
  GraphQL: '#e10098',
  Groovy: '#4298b8',
  HCL: '#844fba',
  HTML: '#e34c26',
  Haskell: '#5e5086',
  Java: '#b07219',
  JavaScript: '#f1e05a',
  JSON: '#292929',
  Julia: '#a270ba',
  'Jupyter Notebook': '#da5b0b',
  Kotlin: '#a97bff',
  Less: '#1d365d',
  Lua: '#000080',
  Makefile: '#427819',
  Markdown: '#083fa1',
  MDX: '#fcb32c',
  Nix: '#7e7eff',
  'Objective-C': '#438eff',
  OCaml: '#ef7a08',
  PHP: '#4f5d95',
  Perl: '#0298c3',
  PowerShell: '#012456',
  Python: '#3572a5',
  R: '#198ce7',
  Ruby: '#701516',
  Rust: '#dea584',
  SCSS: '#c6538c',
  Sass: '#a53b70',
  Scala: '#c22d40',
  Shell: '#89e051',
  Solidity: '#aa6746',
  SQL: '#e38c00',
  Svelte: '#ff3e00',
  Swift: '#f05138',
  TOML: '#9c4221',
  TeX: '#3d6117',
  Twig: '#c1d026',
  TypeScript: '#3178c6',
  Vue: '#41b883',
  WebAssembly: '#04133b',
  XML: '#0060ac',
  YAML: '#cb171e',
  Zig: '#ec915c',
}

export function languageColor(language: string): string {
  const known = colors[language]
  if (known) return known
  let hash = 0
  for (const char of language) hash = (hash * 31 + char.charCodeAt(0)) | 0
  return `hsl(${Math.abs(hash) % 360}, 45%, 55%)`
}

/** File extension to language, for the Any Repo layer where GitHub gives only paths. */
const extensions: Record<string, string> = {
  astro: 'Astro',
  bat: 'Batchfile',
  c: 'C',
  h: 'C',
  cs: 'C#',
  cpp: 'C++',
  cc: 'C++',
  hpp: 'C++',
  css: 'CSS',
  clj: 'Clojure',
  coffee: 'CoffeeScript',
  dart: 'Dart',
  ex: 'Elixir',
  exs: 'Elixir',
  elm: 'Elm',
  erl: 'Erlang',
  fs: 'F#',
  go: 'Go',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  groovy: 'Groovy',
  gradle: 'Groovy',
  tf: 'HCL',
  html: 'HTML',
  htm: 'HTML',
  hs: 'Haskell',
  java: 'Java',
  js: 'JavaScript',
  mjs: 'JavaScript',
  cjs: 'JavaScript',
  jsx: 'JavaScript',
  json: 'JSON',
  jl: 'Julia',
  ipynb: 'Jupyter Notebook',
  kt: 'Kotlin',
  kts: 'Kotlin',
  less: 'Less',
  lua: 'Lua',
  md: 'Markdown',
  mdx: 'MDX',
  nix: 'Nix',
  m: 'Objective-C',
  ml: 'OCaml',
  php: 'PHP',
  pl: 'Perl',
  ps1: 'PowerShell',
  py: 'Python',
  r: 'R',
  rb: 'Ruby',
  rs: 'Rust',
  scss: 'SCSS',
  sass: 'Sass',
  scala: 'Scala',
  sh: 'Shell',
  bash: 'Shell',
  zsh: 'Shell',
  sol: 'Solidity',
  sql: 'SQL',
  svelte: 'Svelte',
  swift: 'Swift',
  toml: 'TOML',
  tex: 'TeX',
  twig: 'Twig',
  ts: 'TypeScript',
  tsx: 'TypeScript',
  mts: 'TypeScript',
  cts: 'TypeScript',
  vue: 'Vue',
  wasm: 'WebAssembly',
  xml: 'XML',
  yml: 'YAML',
  yaml: 'YAML',
  zig: 'Zig',
}

const fileNames: Record<string, string> = {
  dockerfile: 'Dockerfile',
  makefile: 'Makefile',
}

export function languageOfPath(path: string): string {
  const file = path.slice(path.lastIndexOf('/') + 1).toLowerCase()
  const byName = fileNames[file]
  if (byName) return byName
  const dot = file.lastIndexOf('.')
  return dot > 0 ? (extensions[file.slice(dot + 1)] ?? 'Other') : 'Other'
}
